### ISSUE TITLE
NameError: global name 'is_connected' is not defined

### ISSUE THREAD

**Issue by vitalWord** [LegallGuillaume/jenkins-role-strategy-api-python#1]
https://github.com/LegallGuillaume/jenkins-role-strategy-api-python/blob/826398ebecd9f4e7f109c94f42916218e173edca/pyjars/rolestrategy.py#L32

```
Traceback (most recent call last):
  File "role.py", line 4, in <module>
    rs = RoleStrategy(url_base, login, password)
  File "C:\Users\Admin\basecamp\gitolite-admin\jenkinsapi\pyjars\rolestrategy.py", line 32, in __init__
    if not is_connected():
NameError: global name 'is_connected' is not defined
```

**Comment by LegallGuillaume** [comment]
hi,
I have forgotten the "self."
I corrected this ! :) Thanks you
